version: 1.2.{build}

skip_non_tags: false

image: Visual Studio 2017

configuration: Release

services:
- mysql
- mssql2014

before_test:
- ps: >-
    function createMySqlDb() {
      $env:MYSQL_PWD="Password12!"
      $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database quermine;" --user=root'
      iex "& $cmd"
    }

    function createSqlServerDb() {
      sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "CREATE DATABASE quermine;" -d "master"
    }

    function setup() {
      createMySqlDb
      createSqlServerDb
    }
    
    setup
    
init:
- ps: >-
    function gitVersion() {
      write-host "Setting version according to the git release tag."
      $branch=$env:APPVEYOR_REPO_TAG_NAME
      $posAfterVchar = $branch.LastIndexOf("v") + 1
      $versionLength = $branch.Length - $posAfterVchar
      $gitVersion=$branch.substring($posAfterVchar, $versionLength)
      $newVersion="$gitVersion"
      write-host "Update appveyor build version to:$newVersion"
      $env:appveyor_build_version="$newVersion"
      appveyor UpdateBuild -Version "$newVersion"
    }
    if ($env:APPVEYOR_REPO_TAG -eq $true) {
      gitVersion
    }
   
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    dotnet restore -v minimal

    nuget restore -Verbosity quiet
build:
  verbosity: minimal
artifacts:
- path: Quermine\**\.nupkg
  name: NuGet
- path: Quermine.MySql\**\.nupkg
  name: NuGet
- path: Quermine.Sqlite\**\.nupkg
  name: NuGet
- path: Quermine.SqlServer\**\.nupkg
  name: NuGet
deploy:
- provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: U909gTvHqZ0NpnlX9zlt7uIjpgecLfDAixvOtApwnfVYseBihEUBnR3mSqV9ASzY
