version: 1.0.{build}
skip_non_tags: false
image: Visual Studio 2017
init:
- ps: "function gitVersion(){\n        write-host \"This gets the version nr from the end of the git release branch (e.g.: v1.4). And updates the appVersion build version with that (the build nr is appended).\"\n\n    $branch=$env:APPVEYOR_REPO_BRANCH\n    \n    $posAfterVchar = $branch.LastIndexOf(\"v\") + 1\n    $versionLength = $branch.Length - $posAfterVchar\n      \n    $gitVersion=$branch.substring($posAfterVchar, $versionLength)\n      \n    $newVersion=\"$gitVersion\"\n     \n    write-host \"Update appveyor build version to:$newVersion\"\n    $env:appveyor_build_version=\"$newVersion\"\n    appveyor UpdateBuild -Version \"$newVersion\"\n}\ngitVersion"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    dotnet restore

    nuget restore
build:
  verbosity: minimal
test: off
artifacts:
- path: Quermine\**\.nupkg
  name: NuGet
- path: Quermine.MySql\**\.nupkg
  name: NuGet
deploy:
- provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: U909gTvHqZ0NpnlX9zlt7uIjpgecLfDAixvOtApwnfVYseBihEUBnR3mSqV9ASzY